version: '3.1'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=postgrespassword
    healthcheck:
      test: exit 0

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:5000
    depends_on:
      - postgres_db
